### ISSUE TITLE
httpd role のファイル削除処理が効いてない

### ISSUE THREAD

**Issue by momonchy** [momonchy/ansible-for-wordpress#2]
roles/httpd の以下処理が効いてない。

```yml
- name: Delete unnecessary files
  file:
    path: "/etc/httpd/conf.d/{{ item }}"
  with_items:
    - autoindex.conf
    - welcome.conf
```
